name: Build RISC-V Toolchain RV64 FULL Newlib

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Run the RISC-V Toolchain build'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y
             autoconf
             automake
             autotools-dev
             curl
             python3
             python3-pip
             libmpc-dev
             libmpfr-dev
             libgmp-dev
             gawk
             build-essential
             bison
             flex
             texinfo
             gperf
             libtool
             patchutils
             bc
             zlib1g-dev
             libexpat-dev
             ninja-build
             git
             cmake
             libglib2.0-dev
             device-tree-compiler
             libboost-regex-dev
             libboost-system-dev
             libboost-all-dev
          
      - name: Build RISC-V Toolchain
        run: |
          export RISCV=/opt/riscv
          export PATH="$PATH:/opt/riscv/bin"
          source ~/.bashrc
          mkdir riscv-64
          cd riscv-64
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          ./configure --prefix=/opt/riscv
          make -j $(nproc)
          cd ..
          git clone https://github.com/riscv-software-src/riscv-isa-sim
          cd riscv-isa-sim
          mkdir build
          cd build
          ../configure --prefix=/opt/riscv
          make -j $(nproc)
          sudo make install
          cd ..
          cd ..
          git clone https://github.com/riscv-software-src/riscv-pk
          cd riscv-pk
          mkdir build
          cd build
          ../configure --prefix=/opt/riscv --host=riscv64-unknown-elf
          make -j $(nproc)
          sudo make install
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv-toolchain-rv64
          path: /opt/riscv
